### PR TITLE
Get the python3 builds working again, start using CircleCI

### PR DESCRIPTION
**Pull request by natoscott**
I found recent commits related to configuration files have regressed the python3 builds of rmtest in various small ways, so I've done some work to fix that up here.  There were also several situations where 'setup.py test' in rmtest has never worked for python3 - I've found time to fix those up now too.  Finally, I've fixed some race conditions and gone through all the code and worked through all the pylint(1) issues.

I've made a start here too at figuring out CircleCI (my first time using it, but its used by many RedisLabs modules I see) in order to get some CI going for the rmtest python module using python3.  There was a number of problems in that process, and I tried several approaches, but I've ended up with something that at least does automated pylint checking, and builds, and provides us a path to running the tests too in the future.  This initial level of CI would have at least caught the current python3 issues.

Running the tests is problematic because of the new dependencies on python3 (not provided by the redislabsmodules/rmbuilder container).  OTOH, using the default python:latest circleci container we do not have redis itself of course - which the tests also need - and getting that into the container is kinda the point of rmbuilder.  Hohum, what to do?  I ended up sticking with rmbuilder and added a note to the .circleci/config.yml file that once we can get that container updated to a new base (Debian 10 will suit, next year), we can re-enable the tests - they're currently commented out though.

cheers.

### CODE REVIEW

**Comment by gkorland** [comment]
@natoscott a new testing framework RLTest replaces the current rmtest see:
https://github.com/RedisLabsModules/RLTest

**Comment by natoscott** [comment]
@gkorland aha, thanks for the heads-up!

Are there no more planned updates for rmtest then?  If that's the case, and since I've been using it in another project, I would be happy to take on maintaining it if y'all no longer plan to - just lemme know.

cheers.

**Comment by natoscott** [comment]
@gkorland @mnunberg I'm still happy to take on maintenance of this python module going forward if noone else intends to.  I would like to merge this PR, tag and release rmtest-1.0 with python3 support and upload it to PyPI, if anyone can help me with the access needed there (I'm user 'scott.nato' on pypi.org).

cheers.

**Review by mnunberg — APPROVED** [review]

**Comment by natoscott** [comment]
@mnunberg could you tag the 1.0.0 release with the python3 support on github and upload to pypi.org?  pypi.org is still out-of-date and states 0.7.0 is latest (and obviously lacks py3 support).

I'm happy to help out there as I mentioned earlier; I know you folk have deprecated use of this code.

**Pull request merged**
